# PostgreSQL database connection

common: &common
  adapter: postgresql
  username: trendfinder
  password: trendfinder3107

development:
  <<: *common
  database: trendfinder_development

test:
  <<: *common
  database: trendfinder_test

production:
  adapter: postgresql
  database: gtf
  username: gtf
  password: gtf675
