# PostgreSQL database connection

common: &common
  adapter: postgresql
  username: trendfinder
  password: trendfinder3107

development:
  <<: *common
  database: trendfinder_development

test:
  <<: *common
  database: trendfinder_test

production:
  adapter: postgresql
  username: globapd6_tf
  password: trendfinder1545
  database: globapd6_trendfinder
